
url: https://manly-games.github.io
baseurl: " "
head_title: Manly Games
footer: Website of Manly Games
favicon: favicon.ico
collections:
  posts:
    permalink: "/blog/:categories/:title/"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
- scope:
    path: ''
  values:
    image: " "
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
feed:
  categories:
  - news
  - devblog
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
